name: mixingandmastering
favicon: null
layout_spectrum: 0.74866
typography_spectrum: 0.6723960137460381
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#709270'
    - '#133513'
    - '#4a6c4a'
    - '#ffffff'
    - '#d9bd86'
  brandStrength: 0.75
  lightness: 0.9750858687330037
  saturation: 0.9357815610710531
  rhythmicContrast: 0.7022801421117038
purpose: []
