name: mixingandmastering
favicon: null
layout_spectrum: 0.74866
typography_spectrum: 0.52494
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#173142'
    - '#ffffff'
    - '#ffcc00'
    - '#807b30'
    - '#afb9c0'
  brandStrength: 0.5
  lightness: 0.9750858687330037
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
